[package]
name = "chip8-emulator"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
clap = { version = "4.5.18", features = ["derive"] }
piston2d-graphics = "0.45.0"
piston_window = "0.132.0"
rand = "0.8.5"
